---
title: "Infographic"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE}
library(ggplot2)
library(dplyr)
library(ggrepel)
library(magrittr)
library(cowplot)
```


```{r, echo = FALSE}
mydata = read.csv("DATA.csv", header=TRUE)
attach(mydata)
subset_data <- subset(mydata, Playoffs == 5)
subset_data <- subset_data[, c("Year", "Team", "Payroll", "Wins","Team")]
all_teams <- c("Yankees", "BlueJays", "RedSox", "Tampa", "Orioles", "WhiteSox", "Royals", "Twins","Tigers", "Guardians", "Astros", "Angels", "Athletics","Mariners", "Rangers", "Mets", "Phillies", "Nationals", "Marlins","Braves,", "Brewers", "Cubs", "Cardinals","Pirates", "Reds", "Giants", "Diamondbacks", "Dodgers", "Rockies", "Padres")
# Subset the data for the specified teams
team_summary <- mydata %>%
  group_by(Team) %>%
  summarize(avg_payroll = mean(Payroll), avg_wins = mean(Wins))
mydata_sub <- mydata[mydata$Team %in% all_teams,]
team_summary <- mydata %>%
  group_by(Team) %>%
  summarize(avg_payroll = mean(Payroll), avg_wins = mean(Wins))
#print(team_summary)
```





```{r, echo = FALSE}
library(tidyverse)
library(waffle) # remotes::install_github("hrbrmstr/waffle")
library(patchwork)
library(lubridate)
library(extrafont)
library(ggtext)
```


```{r, echo = FALSE}


# Set theme for all plots: 

my_font <- "Arial"

mydata_sub <- mydata[mydata$Team %in% all_teams,]

# Create a vector of team names
teams <- c("Yankees", "WhiteSox", "Royals", "RedSox", "Phillies", "Nationals", "Marlins", "Giants", "Diamondbacks", "Cubs", "Cardinals", "Braves", "Astros", "Angels")

# Subset data for selected teams
team_payroll <- team_summary$Payroll[team_summary$Team %in% teams]

# Create histogram
#HIST_WINNERS = ggplot(data.frame(Payroll = team_payroll), aes(x = Payroll)) +
  #geom_histogram(fill = "green", color = "white", bins = 15) +
  #ggtitle("Payroll Distribution of World Series Winners") +
  #xlab("Payroll (in millions)") +
  #ylab("Frequency")



REGRESSION_WS = ggplot(subset_data, aes(x = Payroll, y = Wins, label = Team)) +
  geom_point() +
  geom_text_repel() +
  xlab("Payroll") +
  ylab("Wins") +
  ggtitle("Scatterplot of Average Wins vs. Average Payroll for Each Team") +
  theme_gray() + geom_smooth(method = "lm", se = FALSE, color = "red") + # Add the linear regression line
  xlab("Payroll") +
  ylab("Wins") +
  ggtitle("Scatterplot of Wins vs. Payroll for World Series Winners")



# Combine plots: 

library(cowplot)



REGRESSION_WS +
  plot_annotation(title = "MLB Success and Payroll, What's the Relationship?",
                  subtitle = "In a sport with no salary cap, how does money behave for winning teams?",
                  caption = "Data: baseballreference.com", 
                  theme = theme(plot.title = element_text(color = "#292929", size = 10, face = "bold", family = my_font),
                                plot.subtitle = element_text(color = "#292929", size = 8, family = my_font),
                                plot.caption = element_text(color = "grey50", face = "bold.italic", family = my_font),
                                plot.background = element_rect("#EBEBEB"),
                                panel.background = element_rect("#EBEBEB")))
```

